const OTP_TYPES = {
  REGISTER_EMAIL: 'REGISTER_EMAIL',
  REGISTER_MOBILE: 'REGISTER_MOBILE',
  FORGOT_PASSWORD_EMAIL: 'FORGOT_PASSWORD_EMAIL',
  FORGOT_PASSWORD_MOBILE: 'FORGOT_PASSWORD_MOBILE',
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  CHANGE_MOBILE: 'CHANGE_MOBILE',
};

const EMAIL_OTP_TYPES = [OTP_TYPES.REGISTER_EMAIL, OTP_TYPES.FORGOT_PASSWORD_EMAIL, OTP_TYPES.CHANGE_EMAIL];
const MOBILE_OTP_TYPES = [OTP_TYPES.REGISTER_MOBILE, OTP_TYPES.FORGOT_PASSWORD_MOBILE, OTP_TYPES.CHANGE_MOBILE];
const REGISTER_OTP_TYPES = [OTP_TYPES.REGISTER_EMAIL, OTP_TYPES.REGISTER_MOBILE];
const FORGOT_PASSWORD_OTP_TYPES = [OTP_TYPES.FORGOT_PASSWORD_EMAIL, OTP_TYPES.FORGOT_PASSWORD_MOBILE];
const CHANGE_OTP_TYPES = [OTP_TYPES.CHANGE_EMAIL, OTP_TYPES.CHANGE_MOBILE];

function isEmailOtpType(type) {
  return EMAIL_OTP_TYPES.includes(type);
}

function isMobileOtpType(type) {
  return MOBILE_OTP_TYPES.includes(type);
}

module.exports = {
  OTP_TYPES,
  EMAIL_OTP_TYPES,
  MOBILE_OTP_TYPES,
  REGISTER_OTP_TYPES,
  FORGOT_PASSWORD_OTP_TYPES,
  CHANGE_OTP_TYPES,
  isEmailOtpType,
  isMobileOtpType,
};
